import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

const RootLayout: React.FC<Props> = async ({
  children,
  params: { locale },
}) => {
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="h-screen flex flex-col gap-14 text-base md:text-lg font-medium text-textPrimary bg-white bg-lightBg bg-center bg-no-repeat">
        <ThemeProvider defaultTheme="system" enableSystem={false} >
          <NextIntlClientProvider messages={messages}>
            <Header />
            <main
              className="flex-grow container"
              dir={locale === "en" ? "ltr" : "rtl"}
            >
              {children}
            </main>
            <Footer />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
